### ISSUE TITLE
Please lock the Ruby version to >= 3.0.0

### ISSUE THREAD

**Issue by mensfeld** [baweaver/dio#1]
While running some analysis against `dio` I noticed, your gem is not locked to 3.0 while using the 3.0 features.
It would be really good if you could specify the `required_ruby_version` in the gemspec. Thanks :)

**Comment by baweaver** [comment]
Yep, will get to that in a moment. Knew I forgot a few things last night. `0.0.1` is, to me, a "here's a cool idea, does it make sense?" type of release so I'll have a few things to work out.

**Comment by mensfeld** [comment]
No problem. Noticed errors with this lib while running it under 27.2 and just thought you forgot to add it :) since you're aware I'll close the issue.

**Comment by baweaver** [comment]
Done, pushed, and released.

**Comment by mensfeld** [comment]
https://my.diffend.io/gems/dio/0.0.1/0.0.2#d2h-099007-196 <3 :)
